This is makeindex, version 2.16 [MiKTeX 22.1].
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....
!! Input index error (file = main.acn, line = 296):
   -- First argument too long (max 10240).
done (295 entries accepted, 1 rejected).
Sorting entries.....done (2577 comparisons).
Generating output file main.acr....done (213 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
